# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: earned_dev

test:
  <<: *default
  database: earned_test

production:
  <<: *default
  database: earned_production
  username: earned
  password: <%= ENV['SEINFELD_DATABASE_PASSWORD'] %>
